In [1]:
import numpy as np


In [5]:
#greatest advantage of numpy - n dimensional array
a=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
#check dimensions of a
a.ndim

2

In [8]:
b=np.array([1,2,3,4,5])
print(b)
#check dimensions of b
b.ndim

[1 2 3 4 5]


1

In [10]:
# shape of b - single row with 5 elements
b.shape

(5,)

In [11]:
#shape of a - a has 2 rows with 5 elements in each row
a.shape

(2, 5)

In [13]:
#get type of a
a.dtype


dtype('int64')

In [14]:
#get type of b
b.dtype

dtype('int64')

In [15]:
#know the size
a.itemsize

8

In [16]:
#get total size
a.nbytes

80

# Working with array elements

a has two rows 0 and 1
from 0th row 3rd element must be extracted - to do so numpy orders the element from 0 to n
therefore number 4 will be the at the location 3 
format -->  arrayname[row_index, column_index]

In [17]:
a[0,3]

4

In [ ]:
# DIY 
# From b extract number 5
b[0, ??]

In [18]:
#use : to extract a complete row

a[0,:]

array([1, 2, 3, 4, 5])

In [19]:
# use : to extract a specific column
a[:, 1]

array([2, 7])

In [36]:
#Replace a row in an array with new set of elements
a[1,:] = [11,12,13,14,15]
print(a)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [37]:
#Replace a specific column with new elements 
a[:,3]=[40,50]
print(a)

[[ 1  2  3 40  5]
 [11 12 13 50 15]]


# Extracting array elements in a sequence

In [24]:
#extract elements with stepsize of 2 from 2rn row of the array a
#array name[row_index,   strat:stop:step]
a[1, 1:4:2]

array([7, 9])

In [25]:
#play around with the following examples
a[1, 1:3:2]

array([7])

In [26]:
a[0, 1:4:1]

array([2, 3, 4])

In [27]:
a[0, 2:3:1]

array([3])

# introducing np.zeros and np.ones

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((2,2)) 

array([[0., 0.],
       [0., 0.]])

In [42]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [43]:
np.zeros((2,2,2,2))  # go on adding dimensions

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [44]:
#matrix with all 1's
np.ones((2,2))   # try with as many diemnsiones you want

array([[1., 1.],
       [1., 1.]])

In [54]:
#identity matrix
np.identity (5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# instead of 0's and 1's we would like to replace with some other element
np.full((2,4), 9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [49]:
# use random numbers to fill the array of any desired shape
np.random.rand(5,3,4)   # try for various dimensions

array([[[0.07116754, 0.83714759, 0.43399719, 0.43489565],
        [0.40757669, 0.11373643, 0.29493395, 0.39048175],
        [0.84641798, 0.59281287, 0.63412242, 0.12909617]],

       [[0.63265583, 0.82410689, 0.47460429, 0.36992976],
        [0.41000526, 0.76105095, 0.24884166, 0.3862794 ],
        [0.60015485, 0.67412347, 0.03951929, 0.33287418]],

       [[0.58618624, 0.02934619, 0.13281949, 0.71657274],
        [0.79453014, 0.48099789, 0.03632594, 0.44727812],
        [0.37532156, 0.48237519, 0.96719393, 0.96761745]],

       [[0.61918208, 0.21495092, 0.47556995, 0.60889842],
        [0.24501099, 0.74336828, 0.38904517, 0.83050389],
        [0.27466216, 0.14093728, 0.15646963, 0.57281785]],

       [[0.58955184, 0.17381636, 0.60963038, 0.96018009],
        [0.07779865, 0.02303149, 0.60869651, 0.38828313],
        [0.08338772, 0.38003244, 0.89668928, 0.41872191]]])

In [51]:
# use random integers  to fill the array
np.random.randint(2,9, size=(4,4))  # 2,9 - integer range  , size=(4,4,)--> dimensions of the matrix

array([[8, 2, 2, 2],
       [8, 2, 5, 8],
       [8, 2, 8, 8],
       [8, 5, 3, 5]])

# Mathematical operations with arrays

In [55]:
a

array([[ 1,  2,  3, 40,  5],
       [11, 12, 13, 50, 15]])

In [57]:
#let's create a new array 
c= np.array([1,2,3,4,5])

In [58]:
c

array([1, 2, 3, 4, 5])

In [59]:
c+2    # every element in the array is incremented by 2

array([3, 4, 5, 6, 7])

In [60]:
c-1   # every element in the original array is decremented by 1

array([0, 1, 2, 3, 4])

In [61]:
c*2    # every element in the array is multiplied by 2

array([ 2,  4,  6,  8, 10])

In [62]:
c/2   # every element in the original array is divided by 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [63]:
c ** 2   # square of every element in an array

array([ 1,  4,  9, 16, 25])

In [64]:
b

array([1, 2, 3, 4, 5])

In [65]:
a

array([[ 1,  2,  3, 40,  5],
       [11, 12, 13, 50, 15]])

In [66]:
a+b   # add two arrays 

array([[ 2,  4,  6, 44, 10],
       [12, 14, 16, 54, 20]])